
const cities = [
    {city : "Głubczyce" , wos :  "opolskie"},
    {city : "Kluczbork" , wos :  "opolskie"},
    {city : "Kaczory" , wos :  "wielkopolskie"},
    {city : "Kalisz" , wos :  "wielkopolskie"},
    {city : "Karpacz" , wos :  "dolnośląskie"},
    {city : "Koniecpol" , wos :  "śląskie"},
    {city : "Kleszczele" , wos :  "podlaskie"},
    {city : "Augustów" , wos :  "podlaskie"},
    {city : "Bełchatów" , wos :  "łódzkie"},
    {city : "Bochnia" , wos :  "małopolskie"},
    {city : "Cedynia" , wos :  "zachodnio-pomorskie"},
    {city : "Cieszyn" , wos :  "śląskie"},
    {city : "Gniezno" , wos :  "wielkopolskie"},
    {city : "Giżycko" , wos :  "warmińsko-mazurskie"},
    {city : "Iława" , wos :  "warmińsko-mazurskie"},
    {city : "Jastrzębie-Zdrój" , wos :  "śląskie"},
    {city : "Knurów" , wos :  "śląskie"},
    {city : "Krosno" , wos :  "podkarpackie"},
    {city : "Lądek-Zdrój" , wos :  "dolnośląskie"},
    {city : "Łowicz" , wos :  "łódzkie"},
    {city : "Malbork" , wos :  "pomorskie"},
    {city : "Płock" , wos :  "mazowieckie"},
    {city : "Pruszków" , wos :  "mazowieckie"},
    {city : "Prószków" , wos :  "opolskie"},
    {city : "Radzymin" , wos :  "mazowieckie"},
    {city : "Sandomierz" , wos :  "świętokrzyskie"},
    {city : "Słupsk" , wos :  "pomorskie"},
    {city : "Szczebrzeszyn" , wos :  "lubelskie"},
    {city : "Świebodzin" , wos :  "lubuskie"},
    {city : "Świdnica" , wos :  "dolnośląskie"},
    {city : "Tłuszcz" , wos :  "mazowieckie"},
    {city : "Wadowice" , wos :  "małopolskie"},
    {city : "Wąchock" , wos :  "świętokrzyskie"},
    {city : "Wieluń" , wos :  "łódzkie"},
    {city : "Wieliczka" , wos :  "małopolskie"},
    {city : "Włocławek" , wos :  "kujawsko-pomorskie"},
    {city : "Złotoryja" , wos :  "dolnośląskie"},
    {city : "Żmigród" , wos :  "dolnośląskie"},
    {city : "Zamość" , wos :  "lubelskie"},
    {city : "Zwierzyniec" , wos :  "lubelskie"}
]

const wos  = {
    "łódzkie": [0, 0],
    "kujawsko-pomorskie": [0.5, 0],
    "pomorskie": [1.5, -0.5],
    "wielkopolskie": [0.5, -0.5],
    "śląskie": [-1.5, 0],
    "opolskie": [-1, -0.5],
    "małopolskie": [-2, 0.5],
    "podkarpackie": [-2, 1],
    "świętokrzyskie": [-1, 0.5],
    "lubelskie": [-0.5, 1],
    "mazowieckie": [0, 0.5],
    "warmińsko-mazurskie": [1.5, 0.5],
    "dolnośląskie": [-1, -1],
    "lubuskie": [0, -1],
    "zachodnio-pomorskie": [1, -1],
    "podlaskie": [1, 1]
}

export  {cities, wos}